// Top-30 tags by frequency from metadata.json (stable — hardcoded per Phase 16 RESEARCH.md)
// Shared constant used by TagMultiSelect and EmptyState
export const TOP_TAGS = [
  'fundraising',
  'real estate',
  'entrepreneurship',
  'digital marketing',
  'marketing strategy',
  'saas',
  'digital transformation',
  'go-to-market strategy',
  'brand strategy',
  'venture capital',
  'artificial intelligence',
  'supply chain',
  'business development',
  'private equity',
  'change management',
  'business scaling',
  'sales strategy',
  'mergers & acquisitions',
  'web development',
  'product development',
  'e-commerce',
  'ai strategy',
  'corporate finance',
  'event management',
  'growth marketing',
  'process optimization',
  'startup scaling',
  'commercial strategy',
  'leadership coaching',
  'financial planning',
]
